=== eugeneshch/JavaTraining/XMLTask/MyLibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.com/MyLibrary" xmlns:tns="http://www.epam.com/MyLibrary">
    <element name="libraries">
    	<complexType>
    		<sequence>
    			<element name="fictionLibrary" type="tns:Library" />
    			<element name="scientificLibrary" type="tns:Library" />
    		</sequence>
    	</complexType>
    </element>
    <simpleType name="LetterType">
    	<restriction base="string">
    		<pattern value="([a-zA-Z])+" />
    	</restriction>
    </simpleType>
    <simpleType name="LetterSpaceType">
    	<restriction base="string">
    		<pattern value="([a-zA-Z\s])+" />
    	</restriction>
    </simpleType>
    <simpleType name="PhoneType">
    	<restriction base="string">
    		<pattern value="([0-9\+\-\s])+" />
    	</restriction>
    </simpleType>
    <complexType name="Library">
    	<sequence>
    		<element name="book" type="tns:Book" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    <complexType name="Book">
    	<sequence>
    		<element name="title" type="string"></element>
    		<element name="author" type="tns:LetterSpaceType"></element>
    		<element name="year" type="gYear"></element>
    		<element name="readers" type="tns:Readers"></element>
    	</sequence>
    	<attribute name="id" type="unsignedInt" use="required" />
    	<attribute name="remainingCopies" type="unsignedByte" use="required" />
    </complexType>
    <complexType name="Readers">
    	<sequence>
    		<element name="reader" type="tns:Reader" minOccurs="0" maxOccurs="unbounded" />
    	</sequence>	
  	</complexType>
  	<complexType name="Reader">
  		<sequence>
    		<element name="fname" type="tns:LetterType"></element>
    		<element name="lname" type="tns:LetterType"></element>
    		<element name="phone" type="tns:PhoneType"></element>
    	</sequence>
  	</complexType>
</schema>

=== eugeneshch/JavaTraining/XMLTask/MyFirstLibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
<lib:libraries xmlns:lib="http://www.epam.com/MyLibrary" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.epam.com/MyLibrary MyLibrary.xsd">
	<fictionLibrary>
		<book id="1" remainingCopies="0">
			<title>Interesting book</title>
			<author>Isaac Asimov</author>
			<year>1960</year>
			<readers>
				<reader>
					<fname>Ivan</fname>
					<lname>Ivanov</lname>
					<phone>+375 29 555-55-55</phone>
				</reader>
				<reader>
					<fname>Petr</fname>
					<lname>Petrov</lname>
					<phone>+375 25 666-66-66</phone>
				</reader>
				<reader>
					<fname>Sidor</fname>
					<lname>Sidorov</lname>
					<phone>8 017 777-77-77</phone>
				</reader>
			</readers>
		</book>
		<book id="2" remainingCopies="25">
			<title>Boring book</title>
			<author>Lev Tolstoi</author>
			<year>1870</year>
			<readers>
				<reader>
					<fname>Lev</fname>
					<lname>Tolstoi</lname>
					<phone>-</phone>
				</reader>
			</readers>
		</book>
	</fictionLibrary>
	<scientificLibrary>
		<book id="3" remainingCopies="3">
			<title>Java book</title>
			<author>Unknown author</author>
			<year>2015</year>
			<readers>
				<reader>
					<fname>Petr</fname>
					<lname>Petrov</lname>
					<phone>+375 25 666-66-66</phone>
				</reader>
			</readers>
		</book>	
		<book id="4" remainingCopies="2">
			<title>Another Java book</title>
			<author>Unknown author</author>
			<year>2012</year>
			<readers>
			</readers>
		</book>	
	</scientificLibrary>
</lib:libraries>
